### ISSUE TITLE
Usage with svelte@next

### ISSUE THREAD

**Issue by Papierkorb** [TheComputerM/svelte-materialify#87]
Hello,

I'm trying to use this library with a `svelte@next` project.  However, I'm running into issues:

Using `svelte-materialify` in `dependencies` or in `devDependencies` throws this error:

```
500

<Button> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

Error: <Button> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at Object.validate_component (/web_modules/svelte/internal.js:1344:15)
    at eval (/_app/routes/index.js:27:13)
    at Object.$$render (/web_modules/svelte/internal.js:1367:22)
    at Object.default (/_app/assets/generated/root.js:38:103)
    at eval (/_app/routes/$layout.js:11:32)
    at Object.$$render (/web_modules/svelte/internal.js:1367:22)
    at eval (/_app/assets/generated/root.js:35:50)
    at $$render (/web_modules/svelte/internal.js:1367:22)
    at Object.render (/web_modules/svelte/internal.js:1375:26)
    at get_response (/home/papierkorb/Projekte/quasar-web/node_modules/@sveltejs/kit/src/renderer/page.js:201:32)
```

Can anyone point me in the right direction?  I'm not even sure if it's a bug of `svelte-materialify`

**Comment by TheComputerM** [comment]
Can you show me your code.

**Comment by Papierkorb** [comment]
Ah sorry, should've added steps to reproduce. 
I created a new project with the following steps that showcases the error: [svelte-next-materialify-broken.zip](https://github.com/TheComputerM/svelte-materialify/files/5747649/svelte-next-materialify-broken.zip)

To create it yourself, first run these commands in an empty directory:

```sh
# Activate TypeScript support, choose SCSS support
$ npm init svelte@next
$ npm i svelte-materialify --dev
$ npm i
```

Second, edit `src/routes/index.svelte` to use svelte-materialify (I used `<Button>`). 
Third, edit `snowpack.config.js` to fix TypeScript:

```diff
-       plugins: ['@snowpack/plugin-typescript'],
+       plugins: [...require('@sveltejs/snowpack-config').plugins,'@snowpack/plugin-typescript'],
```


Fourth run `$ npm run dev` and visit http://localhost:3000/ to see the error.

**Comment by Florian-Schoenherr** [comment]
See #132
